lsi: false
safe: true
source: https://github.com/afrozenator/afrozenator.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
twitter_username: afrozenator
github_username:  afrozenator
