# Check out: https://github.com/pranjaldhole/science-blog-template/

title: Afroz's Blog
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

